In [1]:
import numpy as np

In [2]:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print(input_features.shape)
input_features

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
target_output = np.array([[0,1,1,1]])
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [4]:
weight_hidden = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6]])
weight_output = np.array([[0.7],[0.8],[0.9]])
lr=0.05

In [5]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [6]:
def sigmoid_der(x):
  return sigmoid(x) * (1-sigmoid(x))

In [10]:
for epoch in range (200000):
  input_hidden = np.dot(input_features, weight_hidden)
  output_hidden = sigmoid(input_hidden)
  input_op = np.dot(output_hidden,weight_output)
  output_op = sigmoid(input_op)
                      
  error_out = ((1/2)*(np.power((output_op - target_output),2)))
  print(error_out.sum())

  derror_douto = output_op- target_output
  douto_dino = sigmoid_der(input_op)
  dino_dwo = output_hidden

  derror_dwo = np.dot(dino_dwo.T, derror_douto * douto_dino)

Streaming output truncated to the last 5000 lines.
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.34794838215653723
0.3479483

In [15]:
#MULTI-LAYER-NETWORK

from numpy import exp, array, random, dot

class NeuronLayer():
    def __init__(self, number_of_neurons, number_of_inputs_per_neuron):
        self.synaptic_weights = 2 * random.random((number_of_inputs_per_neuron, number_of_neurons)) - 1

class NeuralNetwork():
    def __init__(self, layer1, layer2):
        self.layer1 = layer1
        self.layer2 = layer2

    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):

            output_from_layer_1, output_from_layer_2 = self.think(training_set_inputs)

            layer2_error = training_set_outputs - output_from_layer_2
            layer2_delta = layer2_error * self.__sigmoid_derivative(output_from_layer_2)

            layer1_error = layer2_delta.dot(self.layer2.synaptic_weights.T)
            layer1_delta = layer1_error * self.__sigmoid_derivative(output_from_layer_1)

            layer1_adjustment = training_set_inputs.T.dot(layer1_delta)
            layer2_adjustment = output_from_layer_1.T.dot(layer2_delta)

            self.layer1.synaptic_weights += layer1_adjustment
            self.layer2.synaptic_weights += layer2_adjustment

    def think(self, inputs):
        output_from_layer1 = self.__sigmoid(dot(inputs, self.layer1.synaptic_weights))
        output_from_layer2 = self.__sigmoid(dot(output_from_layer1, self.layer2.synaptic_weights))
        return output_from_layer1, output_from_layer2

    def print_weights(self):
        print("    Layer 1 (4 neurons, each with 3 inputs):")
        print(self.layer1.synaptic_weights)
        print("    Layer 2 (1 neuron, with 4 inputs):")
        print(self.layer2.synaptic_weights)

if __name__ == "__main__":

    random.seed(1)

    # layer 1 (4 neurons, each with 3 inputs)
    layer1 = NeuronLayer(4, 3)

    # layer 2 (a single neuron with 4 inputs)
    layer2 = NeuronLayer(1, 4)

    neural_network = NeuralNetwork(layer1, layer2)

    print("Stage 1) Random starting synaptic weights: ")
    neural_network.print_weights()

    training_set_inputs = array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1], [0, 0, 0]])
    training_set_outputs = array([[0, 1, 1, 1, 1, 0, 0]]).T

    neural_network.train(training_set_inputs, training_set_outputs, 60000)

    print("Stage 2) New synaptic weights after training: ")
    neural_network.print_weights()

    print("Stage 3) Considering a new situation [1, 1, 0] -> ?: ")
    hidden_state, output = neural_network.think(array([1, 1, 0]))
    print(output)

Stage 1) Random starting synaptic weights: 
    Layer 1 (4 neurons, each with 3 inputs):
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
    Layer 2 (1 neuron, with 4 inputs):
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
Stage 2) New synaptic weights after training: 
    Layer 1 (4 neurons, each with 3 inputs):
[[ 0.3122465   4.57704063 -6.15329916 -8.75834924]
 [ 0.19676933 -8.74975548 -6.1638187   4.40720501]
 [-0.03327074 -0.58272995  0.08319184 -0.39787635]]
    Layer 2 (1 neuron, with 4 inputs):
[[ -8.18850925]
 [ 10.13210706]
 [-21.33532796]
 [  9.90935111]]
Stage 3) Considering a new situation [1, 1, 0] -> ?: 
[0.0078876]


In [19]:
#SIMPLE LAYER NETWORK
from numpy import exp, array, random, dot
try:
    xrange
except NameError:
    xrange = range

class NeuralNetwork():
    def __init__(self):

        random.seed(1)

        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    def __sigmoid_derivative(self, x):
        return x * (1 - x)


    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in xrange (number_of_training_iterations):

            output = self.think(training_set_inputs)

            error = training_set_outputs - output

            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            self.synaptic_weights += adjustment

    def think(self, inputs):

        return self.__sigmoid(dot(inputs, self.synaptic_weights))


if __name__ == "__main__":

    neural_network = NeuralNetwork()

    print ("Random starting synaptic weights: ")
    print (neural_network.synaptic_weights)

    training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    neural_network.train(training_set_inputs, training_set_outputs, 10000)

    print ("New synaptic weights after training: ")
    print (neural_network.synaptic_weights)

    print ("Considering new situation [1, 0, 0] -> ?: ")
    print (neural_network.think(array([1, 0, 0])))

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Considering new situation [1, 0, 0] -> ?: 
[0.99993704]
